apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartedu-app
  labels:
    app: smartedu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartedu-app
  template:
    metadata:
      labels:
        app: smartedu-app
    spec:
      containers:
      - name: smartedu-app
        image: bulawesley/smartedu:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smartedu-app-service
  labels:
    app: smartedu-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: smartedu-app
